#!/bin/sh
set -eu

cat >/usr/share/nginx/html/env-config.js <<EOF
window.__APP_CONFIG__ = {
  REACT_APP_API_BASE_URL: "${REACT_APP_API_BASE_URL:-https://api.bimats.com/coffee/1}",
  REACT_APP_ASGARDEO_CLIENT_ID: "${REACT_APP_ASGARDEO_CLIENT_ID:-REPLACE_WITH_ASGARDEO_CLIENT_ID}",
  REACT_APP_ASGARDEO_BASE_URL: "${REACT_APP_ASGARDEO_BASE_URL:-https://iam.bimats.com}",
  REACT_APP_RESOURCE_SERVER_URL: "${REACT_APP_RESOURCE_SERVER_URL:-https://api.bimats.com}",
  REACT_APP_SITE_URL: "${REACT_APP_SITE_URL:-}",
  REACT_APP_SIGN_IN_REDIRECT_URL: "${REACT_APP_SIGN_IN_REDIRECT_URL:-}",
  REACT_APP_SIGN_OUT_REDIRECT_URL: "${REACT_APP_SIGN_OUT_REDIRECT_URL:-}"
};
EOF