services:
  traefik:
    image: traefik:latest
    container_name: traefik
    profiles:
      - local
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - web

  coffee-api:
    image: bimdevops/coffee-api:1.0.1
    pull_policy: always
    container_name: coffee-api
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=enterprise_net
      - traefik.http.routers.coffee-api.rule=Host(`coffee-api.bimats.net`)
      - traefik.http.routers.coffee-api-http.rule=Host(`coffee-api.bimats.net`)
      - traefik.http.routers.coffee-api-http.entrypoints=web
      - traefik.http.routers.coffee-api-http.service=coffee-api
      - traefik.http.routers.coffee-api.entrypoints=websecure
      - traefik.http.routers.coffee-api.tls=true
      - traefik.http.routers.coffee-api.tls.certresolver=letsencrypt
      - traefik.http.services.coffee-api.loadbalancer.server.port=3000
    networks:
      - web

  coffee-ui:
    image: bimdevops/coffee-ui:1.0.2
    pull_policy: always
    container_name: coffee-ui
    restart: unless-stopped
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-https://api.bimats.com/coffee/1}
      REACT_APP_ASGARDEO_CLIENT_ID: ${REACT_APP_ASGARDEO_CLIENT_ID}
      REACT_APP_ASGARDEO_BASE_URL: ${REACT_APP_ASGARDEO_BASE_URL:-https://iam.bimats.com}
      REACT_APP_RESOURCE_SERVER_URL: ${REACT_APP_RESOURCE_SERVER_URL:-https://api.bimats.com}
      REACT_APP_SITE_URL: ${REACT_APP_SITE_URL:-https://coffee-shop.bimats.net}
      REACT_APP_SIGN_IN_REDIRECT_URL: ${REACT_APP_SIGN_IN_REDIRECT_URL:-https://coffee-shop.bimats.net/}
      REACT_APP_SIGN_OUT_REDIRECT_URL: ${REACT_APP_SIGN_OUT_REDIRECT_URL:-https://coffee-shop.bimats.net/}
    depends_on:
      - coffee-api
    labels:
      - traefik.enable=true
      - traefik.docker.network=enterprise_net
      - traefik.http.routers.coffee-ui.rule=Host(`coffee-shop.bimats.net`)
      - traefik.http.routers.coffee-ui-http.rule=Host(`coffee-shop.bimats.net`)
      - traefik.http.routers.coffee-ui-http.entrypoints=web
      - traefik.http.routers.coffee-ui-http.service=coffee-ui
      - traefik.http.routers.coffee-ui.entrypoints=websecure
      - traefik.http.routers.coffee-ui.tls=true
      - traefik.http.routers.coffee-ui.tls.certresolver=letsencrypt
      - traefik.http.services.coffee-ui.loadbalancer.server.port=80
    networks:
      - web

volumes:
  traefik_letsencrypt:

networks:
  web:
    external: true
    name: enterprise_net
